-- EX1
CREATE TABLE CUSTOMERS (
    CUST_ID VARCHAR(10) PRIMARY KEY,
    CITY VARCHAR(10)
);

-- EX2
CREATE TABLE ORDERS (
    CUST_ID VARCHAR(10) ,
    ORDERDT VARCHAR(8),
    NUMORDER NUMBER(5),
    CONSTRAINT FK_ID FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS(CUST_ID) ON DELETE CASCADE
);

-- EX3
INSERT INTO CUSTOMERS VALUES ('AAA', '서울');
INSERT INTO CUSTOMERS VALUES ('CCC', '서울');
INSERT INTO CUSTOMERS VALUES ('DDD', '부산');

-- EX4
INSERT INTO ORDERS VALUES('AAA', '20170120', 1);
INSERT INTO ORDERS VALUES('BBB', '20170124', 1);
