-- CREATE TABLE
create table DELIVERY (
    D_ID NUMBER(5),
    PSEQ NUMBER(5),
    D_COMPANY VARCHAR2(3)
);
-- INPUT DATA
INSERT INTO DELIVERY VALUES (10000, 10, 'LOGEN');
-- MODIFY COLUMN DELIVERY
ALTER TABLE DELIVERY MODIFY D_COMPANY VARCHAR2(100);
-- D_ID -> DELIVERY_NO
ALTER TABLE DELIVERY RENAME COLUMN D_ID TO DELIVERY_NO;
-- DELETE
ALTER TABLE DELIVERY DROP COLUMN PSEQ;
DESC DELIVERY;